steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}:${COMMIT_SHA}
      - -t
      - ${_IMAGE}:latest
      - .

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}:${COMMIT_SHA}

  - id: PushLatest
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}:latest

  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_IMAGE}:${COMMIT_SHA}
      - --region=${_DEPLOY_REGION}
      - --platform=managed
      - --service-account=${_RUNTIME_SA}
      - --allow-unauthenticated
      - --memory=512Mi
      - --quiet

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DEPLOY_REGION: europe-west1
  _SERVICE_NAME: daikin-dashboard
  _RUNTIME_SA: daikin-dashboard@${PROJECT_ID}.iam.gserviceaccount.com
  _IMAGE: europe-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/daikin-dashboard/daikin-dashboard

images:
  - ${_IMAGE}:${COMMIT_SHA}
  - ${_IMAGE}:latest
